### PR TITLE
convert config_hash to array to preserve ordering

### PR DESCRIPTION
**Pull request by GeoffWilliams**
Converted `config_hash` to be an array as I was getting random ordering in the config file otherwise

### CODE REVIEW

**Comment by thias** [comment]
I have now forced sorting of the hash keys. For all of the generic configuration file options, it shouldn't be an issue, but for people building ACLs with it, it might. What do you think of having both the existing parameter and an additional `$config_array` and document the behavior different between both? (updated PR welcome! ;-))

**Comment by GeoffWilliams** [comment]
Hmm that could prevent the need for users who have already deployed from having to recode things but the ACL behaviour is a nasty gotcha that would be good to protect users from.

I'd personally like to see passing an array of config options be the preferred way of doing things, otherwise we would need to look at prefixing hash keys with numbers, etc, to maintain the correct ordering.

How about this:
1. accept a `$config` as in the original PR
2. still accept the `$config_hash` variable but log a deprecation warning if its used
3. if both `$config` and `$config_hash` are set, fail compilation
4. in the template, iterate both `$config` and `$config_hash` since only one can ever be set
5. update documentation to reflect this
6. at some point in the distant future, plan on removing the `$config_hash` variable
?

I'm not keen on having 2 first class ways of passing in the extra config fields without indicating to users which one they should be using.  How does this sound to you?  I can certainly try and put something together if this looks ok

**Comment by thias** [comment]
I personally find `$config` too vague anyway, which is why I has suggested `$config_array`. I sort of liked the hash for the ease of aligning the key+values nicely :-) Unfortunately puppet's limitations do make it quite tricky here...

I would be fine having both, and updating the README to make it clear that the array should be preferred, but that the hash is still there for legacy reasons and may still be used for lines where the order in the configuration file is known to not be important (I can update the README and CHANGELOG after accepting your code change).

**Comment by GeoffWilliams** [comment]
that sounds good to me. I'll have a go at this next time I get a moment.  Hashes aren't ordered in most programming languages unless your using a variety that guarantees it so not Puppet's fault this time ;-)

**Comment by GeoffWilliams** [comment]
have squashed and re-based - I'll leave the documentation update to you if thats ok?  thanks!

**Comment by thias** [comment]
Sorry for the loooooooooooong delay!

**Pull request merged**
