### PR TITLE
operatingsystemrelease changed to operatingsystemMAJrelease.

### PR DESCRIPTION
**Pull request by f3rr**
Compatibility for EL7

### CODE REVIEW

**Comment by f3rr** [comment]
word fully work with EL7, because templates are not working under EL7, but you can at least use with custom defined template. If i get some time, i try to finish EL7 support fully.

**Comment by eperdeme** [comment]
Will this work on future parser / puppet v4?

I get the error;

Error 400 on SERVER: Evaluation Error: Comparison of: String < Integer, is not possible. Caused by 'A String is not comparable to a non String'.

**Comment by eperdeme** [comment]
Another author has done;

  if versioncmp($::operatingsystemrelease,'6') < 0 {

https://github.com/pecastro/puppet-squid3/commit/e6c33e979f3351685057277c9ab0f9e481cec430

**Comment by f3rr** [comment]
youre right. I will change it soon. And make separate request for logformat parameter.

**Comment by thias** [comment]
Yes, the change in #27 has been merged at last. I'll be including the `logformat` change shortly.

**Pull request closed without merging**
